### PR TITLE
Greatly improve `clone!` proc macro error output

### LINKED ISSUE #956: [BUG] `clone!` loses closure arguments span information, leading to poor diagnostics
**Bug description**

If you provide a closure to the `clone!` macro that takes the wrong number of arguments, you'll get a diagnostic like this:

```
error[E0593]: closure is expected to take 4 arguments, but it takes 0 arguments
   --> src/places_sidebar.rs:301:25
    |
301 |               drop_target.connect_drop(clone!(@weak item => move || {
    |  _________________________^^^^^^^^^^^^_-
    | |                         |
    | |                         expected closure that takes 4 arguments
302 | |             }));
    | |______________- takes 0 arguments
    |
help: consider changing the closure to take and ignore the expected arguments
    |
301 |             drop_target.connect_drop(|_, _, _, _|);
    | 
```

This is because rustc is unable to determine the span of the closure arguments, so it falls back to the span of the entire closure. I believe we should be able to thread the correct span back to rustc if we emit the expanded closure arguments with the same span as the original closure. That would lead to a diagnostic like this:

```
error[E0593]: closure is expected to take 4 arguments, but it takes 0 arguments
   --> src/places_sidebar.rs:301:25
    |
301 |               drop_target.connect_drop(clone!(@weak item => move || {
    |                           ^^^^^^^^^^^^                           -- takes 0 arguments
    |                           |
    |                           expected closure that takes 4 arguments
302 |               }));
    |
    |
help: consider changing the closure to take and ignore the expected arguments
    |
301 |             drop_target.connect_drop(clone!(@weak item => move |_, _, _, _| {;
    | 
```

**Backtrace**

N/A

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #956.

What is it this PR doing? Instead of using `panic!` whenever we encounter an invalid input, it generates a `compile_error!` call with the span of the token which created the issue to trick the compiler into given the location we want.

Unfortunately, the spans are limited with stable rustc so I can't use `Span::join` to make it look better in some cases, but I think it remains a great improvement nonetheless.

### CODE REVIEW

File: glib-macros/src/clone.rs [hunk 1]
```diff
@@ -3,12 +3,100 @@
...
+            stream.extend(tokens);
+            let mut t = TokenTree::Group(Group::new(Delimiter::Brace, stream));
+            t.set_span(span);
+
+            let mut stream = TokenStream::new();
+            stream.extend(vec![t]);
+            stream
+        } else {
+            // for some reason there is no span yet...
+            panic!("{message}");
```
Comment (jf2048) [inline glib-macros/src/clone.rs:95]: Could it fall back to `Span::call_site` instead of panicking? That should be equivalent but without the weird "proc macro panicked" messages.

**Review by jf2048 — CHANGES_REQUESTED** [review]

**Review by sdroege — COMMENTED** [review]
Looks good to me otherwise

File: glib-macros/src/clone.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply glib-macros/src/clone.rs:95]: Ah sure.

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by sdroege — APPROVED** [review]
