### PR TITLE
 Fix cairo FFI types name

### LINKED ISSUE #550: Fix cairo FFI types name
A lot of cairo FFI types are misnamed (I discovered it while working on https://github.com/gtk-rs/gtk-rs-core/pull/549). It'd be better to use the "real" names instead.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #550.

### CODE REVIEW

File: cairo/src/context.rs [hunk 1]
```diff
@@ -727,56 +732,40 @@ impl Context {
...
     #[doc(alias = "cairo_font_extents")]
     pub fn font_extents(&self) -> Result<FontExtents, Error> {
-        let mut extents = FontExtents {
-            ascent: 0.0,
-            descent: 0.0,
-            height: 0.0,
-            max_x_advance: 0.0,
-            max_y_advance: 0.0,
-        };
+        let mut extents = FontExtents::new();
```
Comment (sdroege) [inline cairo/src/context.rs:735]:
```suggestion
        let mut extents = MaybeUninit::uninit();
```

or `::zeroed()` maybe?

I don't think we need a constructor for this type at all, do we?

File: cairo/src/context.rs [hunk 2]
```diff
@@ -727,56 +732,40 @@ impl Context {
...
     pub fn text_extents(&self, text: &str) -> Result<TextExtents, Error> {
-        let mut extents = TextExtents {
-            x_bearing: 0.0,
-            y_bearing: 0.0,
-            width: 0.0,
-            height: 0.0,
-            x_advance: 0.0,
-            y_advance: 0.0,
-        };
+        let mut extents = TextExtents::new();
```
Comment (sdroege) [inline cairo/src/context.rs:746]: Same

File: cairo/src/context.rs [hunk 3]
```diff
@@ -727,56 +732,40 @@ impl Context {
...
     pub fn glyph_extents(&self, glyphs: &[Glyph]) -> Result<TextExtents, Error> {
-        let mut extents = TextExtents {
-            x_bearing: 0.0,
-            y_bearing: 0.0,
-            width: 0.0,
-            height: 0.0,
-            x_advance: 0.0,
-            y_advance: 0.0,
-        };
+        let mut extents = TextExtents::new();
```
Comment (sdroege) [inline cairo/src/context.rs:761]: Same

File: cairo/src/font/scaled_font.rs [hunk 4]
```diff
@@ -99,55 +98,39 @@ impl ScaledFont {
...
     #[doc(alias = "cairo_scaled_font_extents")]
     pub fn extents(&self) -> FontExtents {
-        let mut extents = FontExtents {
-            ascent: 0.0,
-            descent: 0.0,
-            height: 0.0,
-            max_x_advance: 0.0,
-            max_y_advance: 0.0,
-        };
+        let mut extents = FontExtents::new();
```
Comment (sdroege) [inline cairo/src/font/scaled_font.rs:101]: same

File: cairo/src/font/scaled_font.rs [hunk 5]
```diff
@@ -99,55 +98,39 @@ impl ScaledFont {
...
     pub fn text_extents(&self, text: &str) -> TextExtents {
-        let mut extents = TextExtents {
-            x_bearing: 0.0,
-            y_bearing: 0.0,
-            width: 0.0,
-            height: 0.0,
-            x_advance: 0.0,
-            y_advance: 0.0,
-        };
+        let mut extents = TextExtents::new();
```
Comment (sdroege) [inline cairo/src/font/scaled_font.rs:110]: same

File: cairo/src/font/scaled_font.rs [hunk 6]
```diff
@@ -99,55 +98,39 @@ impl ScaledFont {
...
     pub fn glyph_extents(&self, glyphs: &[Glyph]) -> TextExtents {
-        let mut extents = TextExtents {
-            x_bearing: 0.0,
-            y_bearing: 0.0,
-            width: 0.0,
-            height: 0.0,
-            x_advance: 0.0,
-            y_advance: 0.0,
-        };
+        let mut extents = TextExtents::new();
```
Comment (sdroege) [inline cairo/src/font/scaled_font.rs:126]: same

File: cairo/src/font/scaled_font.rs [hunk 7]
```diff
@@ -180,9 +163,9 @@ impl ScaledFont {
                 y,
                 text.as_ptr(),
                 text_length,
-                &mut glyphs_ptr,
+                &mut glyphs_ptr as *mut _ as *mut _,
                 &mut glyph_count,
-                &mut clusters_ptr,
+                &mut clusters_ptr as *mut _ as *mut _,
```
Comment (sdroege) [inline cairo/src/font/scaled_font.rs:168]: Add some more explicit casts here, but also only one cast should be needed

Comment (sdroege) [reply cairo/src/font/scaled_font.rs:168]: Also explicit casts elsewhere

File: cairo/src/context.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply cairo/src/context.rs:735]: We don't but I found it better this way.

File: cairo/src/font/scaled_font.rs (hunk 7 above)
Comment (GuillaumeGomez) [reply cairo/src/font/scaled_font.rs:168]: No because we first need to convert from `&mut` to `*mut` and then to the correct pointer type. However I'll update for explicit cast.

File: cairo/src/context.rs (hunk 1 above)
Comment (sdroege) [reply cairo/src/context.rs:735]: It's unnecessarily noisy. We use `MaybeUninit` elsewhere for out parameters too

Comment (sdroege) [reply cairo/src/context.rs:735]: Also it somewhat hides the fact that this is an out parameter. Could as well be an in-out parameter from your code, but what we really expect here is to provide some memory to the function that is then filled/initialized.

Comment (GuillaumeGomez) [reply cairo/src/context.rs:735]: Fine by me!

**Comment by GuillaumeGomez** [comment]
Updated!

**Review by sdroege — APPROVED** [review]
