### PR TITLE
Make stronger guarantees on `ToValue`

### LINKED ISSUE #4: impl ValueType for Value should be a no-op.
# Problem
`Value::get()` looks like it should act like `std::convert::TryInto` but it doesn't.

```rust
let x: Value = 0i32.to_value();
let y: Value = x.get().unwrap();
```

The above panics with `WrongValueType(ValueTypeMismatchError { actual: gint, requested: GValue })`

The above code expects the Value to be a Boxed Value.

What this means is that if a function returns a T: ValueType. It is impossible for that T to be a generic (unknown) Value).

an example from gtk-rs/gtk4-rs#332

`TreemodelExtManual::get() -> Value` does not have the same semantics as `TreeModelExtManual::get<T: ValueType>() -> T` as it is not possible to get an untouched Value from it.

# Possible Solution

Make `impl ValueType for Value` act as a no-op. Similar to how `impl<T> From<T> for T` acts.

The existing behaviour of a boxed value could be created by having a `impl ValueType for Box<Value>` or even a `struct Boxed(pub Value)`

### PR DESCRIPTION
**Pull request by piegamesde**
This more or less reverts https://github.com/gtk-rs/glib/commit/390ca3a2 ("Don't implement ToValue for Value").

Closes #4.

To be honest, I'm not 100% sure if this is the best way forward. The traits and trait bounds are really convoluted and hard to keep track of. For example, I don't know how well this works for `SendValue`. Let me know what you think.

### CODE REVIEW

File: glib/src/value.rs [hunk 1]
```diff
@@ -454,6 +462,42 @@ impl Uninitialized for Value {
...
+    fn to_value(&self) -> Value {
+        self.clone()
+    }
+
+    fn value_type(&self) -> Type {
+        self.type_()
+    }
+}
+
+pub struct NopChecker;
```
Comment (sdroege) [inline glib/src/value.rs:475]: What is this good for and why is it public?

File: glib/src/value.rs [hunk 2]
```diff
@@ -454,6 +462,42 @@ impl Uninitialized for Value {
     }
 }
 
+impl ToValue for Value {
```
Comment (sdroege) [inline glib/src/value.rs:465]:
```suggestion
impl<'a> ToValue for &'a Value {
```

Would (also) be useful to have. Can you add that?

File: glib/tests/value.rs [hunk 3]
```diff
@@ -0,0 +1,13 @@
+use glib::*;
+
+/// Test that `ToValue` (and conversely, `FromValue`) uphold the promised invariants
+#[test]
+pub fn to_value_invariants() {
+    // Inverse
+    assert_eq!(0i32, 0i32.to_value().get().unwrap());
```
Comment (sdroege) [inline glib/tests/value.rs:7]:
```suggestion
    assert_eq!(0i32, 0i32.to_value().get::<i32>().unwrap());
```

File: glib/src/value.rs [hunk 4]
```diff
@@ -246,6 +246,14 @@ where
 }
 
 /// Trait to convert a value to a `Value`.
+///
+/// Similar to other common conversion traits, the following invariants are guaranteed:
+/// 
+/// - **Invertibility**: `x.to_value().get().unwrap() == x`. In words, `FromValue` is the inverse of `ToValue`.
+/// - **Idempotence**: `x.to_value() == x.to_value().to_value()`.
+///   In words, applying `ToValue` multiple times yields the same result as applying it once.
+///   Idempotence also applies the other way around: `value.get::<Value>()` is a no-op.
```
Comment (sdroege) [inline glib/src/value.rs:255]: That last part is not actually implemented here, is it?

Comment (piegamesde) [reply glib/src/value.rs:255]: Yes it is. The tests do `.to_value().get::<Value>().unwrap().get().unwrap()`.

File: glib/src/value.rs (hunk 1 above)
Comment (piegamesde) [reply glib/src/value.rs:475]: It an unfortunate detail of the `FromValue` trait, see the lines that follow. It requires a `ValueTypeChecker` and it must be public. The existing `ValueTypeChecker` implementations didn't fit the current situation, so I had to write another one.

File: glib/src/value.rs (hunk 4 above)
Comment (sdroege) [reply glib/src/value.rs:255]: Hm, where does the `FromValue` impl for `Value` come from?

Comment (sdroege) [reply glib/src/value.rs:255]: Oh!

File: glib/src/value.rs (hunk 1 above)
Comment (sdroege) [reply glib/src/value.rs:475]: Makes sense

File: glib/tests/value.rs (hunk 3 above)
Comment (piegamesde) [reply glib/tests/value.rs:7]: I don't understand why this is required. The test compiles for me without it. But I've also seen the CI fail on this, and that's confusing.

**Comment by piegamesde** [comment]
Maybe @mehmooda have a look on this too?

File: glib/src/value.rs [hunk 5]
```diff
@@ -246,6 +246,14 @@ where
...
+
```
Comment (sdroege) [inline glib/src/value.rs:256]: Maybe add a comment here about `BoxedValue` for the rare case to actually store a `Value` inside a `Value`

File: glib/src/value.rs [hunk 6]
```diff
@@ -454,6 +462,62 @@ impl Uninitialized for Value {
...
+}
+
+pub struct NopChecker;
+
+unsafe impl ValueTypeChecker for NopChecker {
+    type Error = std::convert::Infallible;
+    fn check(_value: &Value) -> Result<(), Self::Error> {Ok(())}
+}
+
+unsafe impl <'a> FromValue<'a> for Value {
```
Comment (sdroege) [inline glib/src/value.rs:492]:
```suggestion
unsafe impl <'a> FromValue<'a> for &'a Value {
```

Too maybe

File: glib/tests/value.rs (hunk 3 above)
Comment (sdroege) [reply glib/tests/value.rs:7]: Yeah also it happens only on that one Windows job for some reason... not sure, it shouldn't be required at all.

**Comment by sdroege** [comment]
Needs a run of `cargo fmt` (in addition to the comments below) but otherwise this seems acceptable to me. @bilelmoussaoui @GuillaumeGomez ?

File: glib/src/value.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply glib/src/value.rs:256]: Please remove this empty line.

File: glib/src/value.rs (hunk 6 above)
Comment (piegamesde) [reply glib/src/value.rs:492]: What for? The method already takes `&self`, there is no owned version. What you suggest would take an `&'a &'a self`, which is weird.

Comment (sdroege) [reply glib/src/value.rs:492]: No, it would return an `&'a Value` instead of a `Value`

Comment (piegamesde) [reply glib/src/value.rs]: Oh, I see.

**Review by sdroege — DISMISSED** [review]
Good for me. How about others?

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Windows CI is still failing though. How weird...

**Comment by piegamesde** [comment]
What do you suggest doing about the windows failure? I'm honestly out of debugging ideas. I could use `#cfg` flags to change the code when built on Windows or to disable that snippet entirely (it's only a test anyways).

**Comment by sdroege** [comment]
Go with `get::<u32>()` and add a FIXME comment above

**Review by sdroege — DISMISSED** [review]

**Comment by sdroege** [comment]
@bilelmoussaoui @GuillaumeGomez So what do you think?

**Comment by GuillaumeGomez** [comment]
I don't have opinion on this topic. I rarely use this type so I'm definitely not sure wether it's better or not...

File: glib/src/value.rs [hunk 7]
```diff
@@ -246,6 +246,16 @@ where
 }
 
 /// Trait to convert a value to a `Value`.
+///
+/// Similar to other common conversion traits, the following invariants are guaranteed:
+///
+/// - **Invertibility**: `x.to_value().get().unwrap() == x`. In words, `FromValue` is the inverse of `ToValue`.
```
Comment (bilelmoussaoui) [inline glib/src/value.rs:252]:
```suggestion
/// - **Invertibility**: `x.to_value().get().unwrap() == x`. In words, [`FromValue`] is the inverse of [`ToValue`].
```
maybe?

**Comment by bilelmoussaoui** [comment]
Otherwise looks fine to me, maybe we should document that the Value is cloned for the `impl ToValue for Value`? _

**Comment by sdroege** [comment]
> maybe we should document that the Value is cloned for the `impl ToValue for Value`?

But where?

**Comment by GuillaumeGomez** [comment]
On the impl?

**Comment by sdroege** [comment]
The way how rustdoc presents docs on impls, almost nobody is reading them. Most people even miss the existence of impls in rustdocs regularly...

**Comment by GuillaumeGomez** [comment]
Then add a note on the trait directly?

**Comment by sdroege** [comment]
Or to that top part where it mentions the properties/relationships between the traits?

**Comment by GuillaumeGomez** [comment]
Or all of the mentioned.

**Comment by sdroege** [comment]
Ok!

**Comment by piegamesde** [comment]
> maybe we should document that the Value is cloned for the impl ToValue for Value?

What for? What would be the alternative the people might expect?

**Comment by sdroege** [comment]
It to be idempotent also in side effects, i.e. not causing copies and the like.

**Comment by piegamesde** [comment]
I added a line about this to the `ToValue` trait documentation. This isn't specific to converting `Value` -> `Value`, thus I don't think it is appropriate on an `impl` block.

**Comment by sdroege** [comment]
Sounds good to me. I'll merge once the CI passes (needs a `cargo fmt` run).

**Comment by piegamesde** [comment]
Argh, I keep forgetting this. There really should be a commit hook or something.

**Comment by GuillaumeGomez** [comment]
> Argh, I keep forgetting this. There really should be a commit hook or something.

Nope. CI is good.

**Comment by sdroege** [comment]
> There really should be a commit hook or something.

Commit hooks are local only, you'd have to somehow install it manually after cloning the repository.
