### PR TITLE
properties: Allow to omit set for construct_only properties

### LINKED ISSUE #1088: property macro: Support construct_only
I have a bunch of

```rust
#[property(get, set, builder().construct_only())]
```

in my code. I don't really need the setter since it will always fail and the `builder().` doesn't look to too pretty. Would it be possible to have something like the following?

```rust
#[property(get, construct_only)]
```

### PR DESCRIPTION
**Pull request by felinira**
This allows to omit `set` for `construct_only` properties, as it is confusing from a semantic perspective, because we don't actually generate a public setter. It was required before, but didn't actually throw an error but panic at runtime.

Updates the docs about how to use `construct_only` and chooses a better example for the `builder()` attribute.

Closes #1088

### CODE REVIEW

**Comment by ranfdev** [comment]
It's still a bit confusing when setting a custom setter, but It's ok. When I'm on the PC I'll propose some small code changes.

File: glib-macros/tests/properties.rs [hunk 1]
```diff
@@ -160,6 +160,10 @@ mod foo {
             weak_ref_prop: glib::WeakRef<glib::Object>,
             #[property(get, set)]
             send_weak_ref_prop: glib::SendWeakRef<glib::Object>,
+            #[property(get, default_value = 0, construct_only)]
```
Comment (bilelmoussaoui) [inline glib-macros/tests/properties.rs:163]: How would a default value work with construct only ?

Comment (pbor) [reply glib-macros/tests/properties.rs:163]: default actually *only* works for construct and construct_only

File: glib-macros/src/lib.rs [hunk 2]
```diff
@@ -862,7 +862,8 @@ pub fn cstr_bytes(item: TokenStream) -> TokenStream {
 /// | `override_interface = expr` | The type of interface of which to override the property from | | `#[property(override_interface = SomeInterface)]` |
 /// | `nullable` | Whether to use `Option<T>` in the wrapper's generated setter |  | `#[property(nullable)]` |
 /// | `member = ident` | Field of the nested type where property is retrieved and set | | `#[property(member = author)]` |
-/// | `builder(<required-params>)[.ident]*` | Used to input required params or add optional Param Spec builder fields | | `#[property(builder(SomeEnum::default()))]`, `#[builder().default_value(1).construct_only()]`, etc.  |
+/// | `construct_only` | Specify that the property is construct only. This will not generate a public setter and only allow the property to be set during object construction. The use of a custom setter is supported. | | `#[property(get, construct_only)]` or `#[property(get, set = set_prop, construct_only)]` |
```
Comment (ranfdev) [inline glib-macros/src/lib.rs:865]:
```suggestion
/// | `construct_only` | Specify that the property is construct only. This will not generate a public setter and only allow the property to be set during object construction. The use of a custom internal setter is supported. | | `#[property(get, construct_only)]` or `#[property(get, set = set_prop, construct_only)]` |
```

File: glib-macros/src/properties.rs [hunk 3]
```diff
@@ -258,6 +259,17 @@ impl PropDesc {
             builder_fields,
         } = attrs;
 
+        let is_construct_only = if builder_fields.iter().any(|(k, _)| *k == "construct_only") {
```
Comment (ranfdev) [inline glib-macros/src/properties.rs:262]: I would define is_construct_only without the `if`, and move the if below:
```
let is_construct_only = builder_fields.iter().any(|(k, _)| *k == "construct_only");
// Insert a default setter automatically
if is_construct_only && set.is_none() {
  set = Some(MaybeCustomFn::Default);
}
```

**Review by ranfdev — CHANGES_REQUESTED** [review]

**Review by ranfdev — APPROVED** [review]

**Review by bilelmoussaoui — APPROVED** [review]
